== CONVENTIONS

This section provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of schema, or special notes regarding how to read the document.

=== Identifiers
The normative provisions in this Standard are denoted by the URI

http://www.opengis.net/spec/ogcapi-geospatial-user-feedback-2/2.0

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

===  Use of HTTPS
For simplicity, this OGC Standard only refers to the HTTP protocol. This is not meant to exclude the use of HTTPS. This is simply a shorthand notation for “HTTP or HTTPS”. In fact, most servers are expected to use HTTPS and not HTTP.

=== Link relations

To express relationships between resources, <<rfc8288,RFC 8288 (Web Linking)>> is used.

The following <<link-relations,registered link relation types [IANA]>> are used in this document.

* **alternate**: Refers to a substitute for this context.

* **collection**: The target IRI points to a resource which represents the user feedback collection resource for the context IRI.

* **next**: Indicates that the link's context is a part of a series, and that the next in the series is the link target.

* **prev**: Indicates that the link's context is a part of a series, and that the previous in the series is the link target.

* **self**: Conveys an identifier for the link's context.

Used in combination with OGC API - Features Part 1: Core or OGC API - Common Part 1: Core, other link relation types will be used, including:

* **http://www.opengis.net/def/rel/ogc/1.0/conformance**: The target IRI refers to a resource that identifies the specifications that the link’s context conforms to.

The following link relation types are specified in the Two Dimensional Tile Matrix Set and Tileset Metadata standard and can be used here:

* **http://www.opengis.net/def/rel/ogc/1.0/geodata**: The target IRI points to a geospatial resource (e.g. a single collection). (Use http://www.opengis.net/def/rel/ogc/1.0/data to point to a list of geospatial resources)

Each resource representation includes an array of links. Implementations are free to add additional links for all resources provided by the API.

=== Schemas

OpenAPI 3.0 Schema objects are used throughout this Standard to define the structure of resources. These schema are typically represented using YAML encoding. This convention is for the ease of the user. It does not prohibit the use of another schema language or encoding. Nor does it indicate that OpenAPI 3.0 Schema objects are required. Implementations should use a schema language and encoding appropriate for the format of the resource. Note that for property values in JSON for which null is not explicitly supported/required, server implementations are recommended to drop the property (as opposed to specifying the property with a value of null).
