== SCOPE

The OGC API - Feedback Standard specifies requirement classes for manage descriptive information provided by users (user feedback) about geospatial resources.

On one hand, a feedback item is the atomic unit of information within a user feedback collection (the equivalent to a user feedback catalogue). It contains metadata provided by users about a specific geospatial resource (e.g. a OGC API collection) or a metadata record. As defined in the OGC Geospatial User Feedback Standard: Conceptual Model. v.2.0, a user feedback item may include user comments, questions and answers, reports of dataset issues and proposed solutions, ratings, usage reports, reproducible usage reports, citations of related datasets or publications describing usage, quality reports, relevant additional provenance information, and significant events related to the use or interpretation of a dataset.

On the other hand, since user feedback items can be grouped into feedback collections, this standard also specifies the "stats" endpoint, which is dedicated to retrieve summary information about the user feedback items contained in a user feedback collection.

The OGC API - Feedback Standard uses and extends on OGC API - Records to describe how user feedback collections can be crawled or searched. Crawling a user feedback collection involves following embedded links from one user feedback item (in a collection) to the next item. Searching a collection of user feedback items involves specifying query predicates that retrieves a subset of user feedback items.

