[[overview]]
== OVERVIEW

=== Role of Geospatial User Feedback

In addition to the metadata provided by the original data provider to describe geospatial resources, many users report that they place greater trust in items that are accompanied by a good user feedback experience. In fact, a study reveals that 84% of people trust brands more when they include User-Generated Content (UGC). We have always relied on word-of-mouth recommendations, but social media has amplified this behavior at scale. UGC is perceived as 2.5 times more authentic than branded content (https://www.social.plus/blog/84-of-people-trust-brands-more-when-they-use-user-generated-content
).

An important element of this trust is not only the linking of datasets to relevant citations in the scholarly literature, but also less formal feedback mechanisms, such as user comments in the form of stories. To avoid locking user feedback into a particular provider, a standardized way to exchange this information has become necessary.

The purpose of providing user feedback about geospatial data is to inform other users and data providers about use cases and experiences with a given geospatial resource (both data and metadata). The goal of this Standard is to facilitate the collection and share of requirements for resources that providers can incorporate into objective quality measures for their products, allowing them to meet the real needs of users and potentially discover new markets for their resources.

To enable simple user interfaces that accommodate different levels of expertise in geospatial data usage, as described in OGC Geospatial User Feedback Standard: Conceptual Model. v.2.0, a feedback item is designed to be as simple as possible while still being comprehensive enough. The following are examples of what the model allows:

    * Commenting, asking questions, and providing answers.
    * Rating data.
    * Citing publications.
    * Providing a quality measure.
    * Documenting additional lineage information.
    * Describing usage.
    * Highlighting a significant event that affects the interpretation of a dataset.

To facilitate the interpretation of a group of user feedback items related to a resource, the need for a user feedback summary became evident. The description of the user feedback summary includes metrics and statistics on all the user feedback items in a user feedback collection or a subset of it, helping users and producers quickly assess a resource.

The conceptual data model for Geospatial User Feedback is covered by the [[[OGC23-017, OGC 23-017]]], _OGC Geospatial User Feedback Standard: Conceptual Model v.2.0_

=== Role of OGC API - Records

https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API - Records] is a standard within the OGC API family that provides a common way to manage geospatial records. It is designed to allow organizations to expose, search, and query metadata records via Web APIs. The OGC API - Records defines a generic structure for record collections and record items, giving flexibility to producers to publish metadata associated with their resources. In addition, its key features are metadata management (allowing the creation, updating, deletion, and querying of geospatial metadata records) and search and retrieval methods.

As feedback can be considered a specific type of metadata produced by users, the flexibility offered by OGC API - Records is used by this Standard to define a specific type of record collection that contains record items conforming to the GUF conceptual model: the user feedback collection and the user feedback item.

=== OGC API Feedback

The OGC API - Feedback defines a <<feedback-item,user feedback item>> as the atomic unit of information in a <<feedback-collection,user feedback collection>>.

A <<feedback-item, user feedback item>> provides a description (metadata) of a resource based on a user experience. The <<fb-item-encoding, user feedback schema>> defined in this Standard includes a set of properties (such as comments, ratings, etc.) that can be used by any user of a certain resource to describe its experience.

A <<feedback-collection, user feedback collection>> is a collection of user feedback items and is defined as a record catalog that conforms to the OGC API - Feedback Standard and only contains user feedback items.

A <<user-feedback-summary,user's feedback summary>> provides an aggregation of information about feedback items contained in a feedback collection, which includes aggregated metrics and key insights from user comments and reports regarding a specific resource. 

An implementation of the OGC API - Feedback enables retrieving a subset of feedback items from a feedback collection using a logically connected set of predicates that may include spatial and/or temporal predicates.

<<fb_API_1>> summarizes the access paths and relation types defined in this Standard.

[#fb_API_1,reftext='{table-caption} {counter:table-num}']
.OGC API - Feedback Paths
[cols="40,20,40",options="header"]
|===
| Path Template| Relation| Resource
3+| *Common*
|/| | Landing page
|/conformance| conformance| Conformance Classes
|/collections | data| Metadata describing the  collections available from this API implementation instance (some of them user feedback collections) 
|/collections/{collectionsId} | collections| Metadata describing a feedback collections which has the unique identifier {collectionsId}
3+| *User Feedback Collection and user feedback items*
|/collections/{collectionsId}/items| items| Search results based on querying the service for feedback records satisfying 0..n query parameters.
|/collections/{collectionsId}/items/{itemsId}|item|User feedback item which has the unique identifier {itemsId}
|/collections/{collectionsId}/stats|summary| User's feedback summary of the feedback items (or a subset of them) contained in a user feedback collection
|===

Where:
* {collectionsId} = An identifier for a specific user feedback collection.
* {itemsId} = An identifier for a specific user feedback item within a feedback collection.

=== Components

OGC API - Feedback is an specific implementation of the OGC API -Records. This Standard, therefore, only describes those components specific of OGC API – Feedback.

The following components may be used to deploy a User Feedback Collection:

1. The core schema of a user feedback item.
2. The definition of a user feedback collection resource that groups and describes a set of related user feedback items (i.e. a feedback catalog).
3. The definition of a user's feedback summary that aggregates information about a set of user feedback items in a user feedback collection.
4. The definition of a core set of query parameters for searchable feedback collection.

Using these components a user feedback collection can be deployed (in the same way as any record collection) as:

* A set of web-accessible User Feedback items that can be crawled by a search engine crawler, using (for example) a web browser, or by using automated tools.
* A searchable User Feedback Collection with user User Feedback Items accessible through an API endpoint.

[[Feedback_schema]]
==== User Feedback item schema

The core set of user feedback properties that may be used to point a resource include the itemIdentifier, abstract, contact, contactRole, dateInfo and target. A complete definition of a user feedback item can be found in clause <<fb_item_props, User feedback properties>>.

The choice of which properties to include is based in the Geospatial User Feedback (GUF) conceptual model [7].

Although this Standard does not mandate any particular encoding for a user feedback item or a user feedback collection, it does define a conformance class for a <<fb-item-encoding,JSON encoding>>.

Other encodings are allowed but are not described in this Standard.

=== User Feedback Collection (catalog)

A <<feedback-collection,User Feedback Collection>> (or a User Feedback Catalog) is a resource that groups and describes a set of related <<feedback-item, User Feedback Items>>. The collection is the primary access point from which a deployed set of user feedbacks can be accessed. Having found a collection, a client can, by following the appropriate hypermedia controls contained therein, navigate to the feedbacks of the collection.

Depending on the deployment pattern, the collection may provide a link to each individual feedback of the collection or a link to a search access point for retrieving subsets of feedbacks.

The core set of properties that may be used to describe a User Feedback Collection are the same properties used to describe a catalog in https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API - Records] including the property **"conformsTo"** signaling that the collection content (the User Feedback Items) conforms to the OGC API - Geospatial User Feedback.

==== User's feedback summary schema

The core set of a user feedback summary that may be used to summarize a feedback collection include numberOfFeedbackItem, minimumRating, maximumRating, averageRating, numberOfRatings, numberOfUserComments, numberOfUsageReports, numberOfReproducibleUsageReports, numberOfCitations, numberOfAdditionalQualities, numberOfAdditionalLineages and  numberOfSignificantEvents. A complete definition of a user feedback summary can be found in the <<user-feedback-summary,Feedback Summary>>.

The choice of which properties to include in the set of core properties is based in the Geospatial User Feedback (GUF) conceptual model [7].

Although this Standard does not mandate any particular encoding for a user's feedback summary, it does define a conformance class for <<fb-summary-encoding,JSON encodings>>.

Other encodings are allowed but are not described in this Standard.

==== Query parameters

A set of <<feedback-query-parameters,query parameters>>, based on the https://docs.ogc.org/is/20-004r1/20-004r1.html[OGC API - Records], can be applied to a searchable user feedback collection endpoint. The complete list of parameters an its use is defined in <<feedback-query-parameters,Feedback Query parameters>> section 

