== *Geospatial User feedback model. Core*

This section describes two requirements classes that are fundamental for encoding Geospatial User Feedback items in XML: the Quality Common and the User Feedback Item.


=== *7.1	Requirements Class Quality Common*

This requirements class defines the XML encoding for data model classes that are common to, and useful for, both quality metadata generated by producers and user feedback metadata. For this reason they are kept in a separate conformance class. In essence, this conformance class represents the foundations for building a user feedback model. This requirements class inherits all the necessary elements from the ISO19115-1:2014 and the ISO19157:2013 metadata models (such as CI_Citation, CI_Date etc) and adds two extra classes for citing publications (QCM_Publications) and for reporting discovery issues (QCM_DiscoveredIssues).


//include::../requirements/requirements_class.adoc[]

include::../requirements/requirement001.adoc[]

include::../requirements/requirement002.adoc[]

include::../requirements/requirement003.adoc[]

include::../requirements/requirement004.adoc[]

include::../requirements/requirement005.adoc[]

The qcm.xsd schema has been derived automatically from the OGC 15-097 UML model. No tables describing the naming of the elements and subelements are reproduced here due to they will be the same specified in the conceptual model.

The following code shows a xml encoding example for QCM_Publication

[source]
<QCM_Publication 
		xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/1.0" 
		xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" 	
		xmlns="http://www.opengis.net/guf/1.0/common" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.opengis.net/guf/1.0/common 
	../qcm.xsd"> 
	<cit:title> 
		<gco:CharacterString>Exploiting synergies of global land cover products for carbon cycle modeling</gco:CharacterString> 
	</cit:title> 
	<cit:date> 
		<cit:CI_Date> 
			<cit:date> 
				<gco:DateTime>2006-01-01T00:00:00Z</gco:DateTime> 
			</cit:date> 
			<cit:dateType> 
				<cit:CI_DateTypeCode codeList="http://wis.wmo.int/2008/catalogues/draft_version_1-1/WMO_Codelists_ver1_1.xml#CI_DateTypeCode" codeListValue="creation"/> 
			</cit:dateType> 
		</cit:CI_Date> 
	</cit:date> 
	<cit:series> 
		<cit:CI_Series> 
			<cit:name> 
				<gco:CharacterString>Remote Sensing of Environment</gco:CharacterString> 
			</cit:name> 
		</cit:CI_Series> 
	</cit:series> 
	<cit:otherCitationDetails> 
		<gco:CharacterString>101 (2006) 534–553</gco:CharacterString> 
	</cit:otherCitationDetails>  
	<motivation><QCM_CitationMotivationCode codeListValue="descrive" codeList="http://www.opengis.net/guf/1.0/resources/codeList.xml#QCM_PublicationCategoryCode"></QCM_CitationMotivationCode></motivation> 
	<category><QCM_PublicationCategoryCode codeListValue="journalArticle" codeList="http://www.opengis.net/guf/1.0/resources/codeList.xml#QCM_Publ+-------
	icationCategoryCode"></QCM_PublicationCategoryCode></category> 
</QCM_Publication> 
----

The following code shows a xml encoding example for QCM_DiscoveredIssue:
[source]
----
<QCM_DiscoveredIssue xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" xmlns="http://www.opengis.net/guf/1.0/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.opengis.net/guf/1.0/common ../qcm.xsd">
	<knownProblem>
		<gco:CharacterString>These maps cannot be used for land cover change detection since the error in the original map is higher than the change detected (e.g. GLC-2000 versus GlobCover). Due  to  the  large  disagreements  between  these  land  cover products, we recommend that the user community does not, by default, use the latest product with the highest resolution, but carefully examines the sensitivity of these products within a speciﬁc application..</gco:CharacterString>
	</knownProblem>
	<workAround>
		<gco:CharacterString> In the situation where the maps are used for national and regional applications, we would recommend examining the disagreement of the products in the areas  of interest and also to compare them with high resolution ground data or aerial photography. One way to do this would be to use geo-wiki.org (Fritz et al 2009), a global land cover validation tool,  which  can  be  used  to  visualize  the  global  land  cover products and the disagreement directly on top of Google Earth. By exploring the discrepancies at the level of an individual country in combination with local knowledge, the user can gain insight into which product is better in a speciﬁc region and which product is better suited for a particular application.  Crowd-sourced  data  in  the  form  of  geo-tagged photos and information collected through Web 2.0 applications like  geo-wiki  and  smart  phones  could  also  be  harnessed as  a  rich  source  of  training  and  calibration  data  for  global land  cover  algorithms. </gco:CharacterString>
	</workAround>
</QCM_DiscoveredIssue>
----
=== *7.2	Requirements Class User Feedback Item*

This requirements class defines the data model classes that are involved in the definition of an individual user feedback item. The GUF model makes an effort to remain as simple as possible but comprehensive enough, in order to allow for simple user interfaces that can cover different levels of expertise on geospatial data usage. The following are examples of what the GUF model allows: commenting, asking questions, providing answers (the GUF_UserComment class), rating data (GUF_Rating), citing publications (QCM_Publication), providing a quality measure (additionalQuality), documenting additional lineage information (additional LineageSteps) or emphasizing a significant event that conditions the interpretation of a dataset (GUF_SignificantEvent). 

Each one of the previous examples is considered an “item” of feedback. Geospatial User Every item is set into a context by a combination of target, citations and scope. Feedback can be provided both about data or metadata.

include::../requirements/requirement006.adoc[]

The guf.xsd schema has been derived automatically from the OGC 15-097 UML model. No tables describing the naming of the elements and subelements are reproduced here due to they will be the same specified in the conceptual model.

The following code shows a xml encoding example for GUF_FeedbackItem

[source]
<GUF_FeedbackItem
				xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0"
				xmlns:mdq="http://standards.iso.org/iso/19157/-2/mdq/1.0" 
				xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0" 
				xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/1.0" 
				xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" 
				xmlns:qcm="http://www.opengis.net/guf/1.0/common" 
				xmlns="http://www.opengis.net/guf/1.0/core"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xmlns:xlink="http://www.w3.org/1999/xlink" 
				xsi:schemaLocation="http://www.opengis.net/guf/1.0/core ../guf.xsd">
	<itemIdentifier>
		<mcc:MD_Identifier>
			<mcc:code>
				<gco:CharacterString>GCL2000_feedack_item_1</gco:CharacterString>
			</mcc:code>
		</mcc:MD_Identifier>
	</itemIdentifier>
	<abstract>
		<gco:CharacterString>Comparson with other land cover products is difficults because legends are not compatible</gco:CharacterString>
	</abstract>
	<contactRole>
		<GUF_UserRoleCode codeListValue="researchEndUser" codeList="">researchEndUser</GUF_UserRoleCode>
	</contactRole>
	<dateInfo>
		<cit:CI_Date>
			<cit:date><gco:DateTime>2006-03-01T00:00:00Z</gco:DateTime></cit:date>
			<cit:dateType>
				<cit:CI_DateTypeCode codeList="http://wis.wmo.int/2008/catalogues/draft_version_1-1/WMO_Codelists_ver1_1.xml#CI_DateTypeCode" codeListValue="creation"/>
			</cit:dateType>
		</cit:CI_Date>				
	</dateInfo>
	<citation>
		<cit:CI_Citation>
			<cit:title>
				<gco:CharacterString>Towards the global monitoring of biodiversity change</gco:CharacterString>
			</cit:title>
			<cit:date>
				<cit:CI_Date>
					<cit:date>
						<gco:DateTime>2006-03-01T00:00:00Z</gco:DateTime>
					</cit:date>
					<cit:dateType>
						<cit:CI_DateTypeCode codeList="http://wis.wmo.int/2008/catalogues/draft_version_1-1/WMO_Codelists_ver1_1.xml#CI_DateTypeCode" codeListValue="creation"/>
					</cit:dateType>
				</cit:CI_Date>
			</cit:date>
			<cit:series>
				<cit:CI_Series>
					<cit:name>
						<gco:CharacterString>TRENDS in Ecology and Evolution</gco:CharacterString>
					</cit:name>
				</cit:CI_Series>
			</cit:series>
			<cit:otherCitationDetails>
				<gco:CharacterString>Vol.21 No.3</gco:CharacterString>
			</cit:otherCitationDetails>
		</cit:CI_Citation>
	</citation>
	<contact>
		<GUF_UserInformation>
			<userDetails>
				<cit:CI_Responsibility>
					<cit:role>
						<cit:CI_RoleCode codeList="http://wis.wmo.int/2008/catalogues/draft_version_1-1/WMO_Codelists_ver1_1.xml#CI_RoleCode" codeListValue="user"/>
					</cit:role>
					<cit:party>
						<cit:CI_Individual>
							<cit:name>
								<gco:CharacterString>Henrique M. Pereira</gco:CharacterString>
							</cit:name>
						</cit:CI_Individual>
					</cit:party>
				</cit:CI_Responsibility>
			</userDetails>
			<expertiseLevel>
				<GUF_RatingCode codeListValue="5" codeList="http://www.opengis.net/guf/1.0/resources/codeList.xml#GUF_RatingCode"></GUF_RatingCode>
			</expertiseLevel>
		</GUF_UserInformation>
	</contact>
	<userComment>
		<GUF_UserComment>
			<comment>
				<gco:CharacterString>Surprisingly,  there  are  no  directly comparable sets of global land-cover data for two different
dates. For instance, the Global Land Cover for the year 2000 (GLC 2000) based on SPOT VEGETATION (http://www-gvm.jrc.it/glc2000) is not directly comparable
with the International Geosphere–Biosphere Programme (IGBP) Land Cover (1992–1993, http://edcdaac.usgs.gov/glcc/globdoc2_0.asp)  based  on  the  National  Oceanic
and  Atmospheric  Administration  Advanced  Very  High Resolution Radiometer (NOAA-AVHRR). The difﬁculties arise from the use of different sensors, different land-cover
classiﬁcation  systems  (including  different  deﬁnitions  of forest)  and  different  classiﬁcation  methods. </gco:CharacterString>
			</comment>
		</GUF_UserComment>
	</userComment>
	<target>
		<GUF_FeedbackTarget>
			<resourceRef xlink:href="http://www-gvm.jrc.it/glc2000">
				<cit:CI_Citation>
					<cit:title></cit:title>
					<cit:identifier>
						<mcc:MD_Identifier>
							<mcc:code>
								<gco:CharacterString>GLC2000</gco:CharacterString>
							</mcc:code>
							<mcc:codeSpace>
								<gco:CharacterString>jrc.ec.europa.eu</gco:CharacterString>
							</mcc:codeSpace>
						</mcc:MD_Identifier>
					</cit:identifier>
				</cit:CI_Citation>
			</resourceRef>
			<scope>
				<mcc:MD_Scope>
					<mcc:level>
						<mcc:MD_ScopeCode codeListValue="dataset" codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codeLists.xml#MD_ScopeCode"/>							
					</mcc:level>
				</mcc:MD_Scope>
			</scope>
			<role>
				<GUF_TargetRoleCode codeListValue="primary" codeList="http://www.opengis.net/guf/1.0/resources/codeList.xml#GUF_TargetRoleCode"></GUF_TargetRoleCode>
			</role>
		</GUF_FeedbackTarget>
	</target>
	<target>
		<GUF_FeedbackTarget>
			<resourceRef xlink:href="http://edcdaac.usgs.gov/glcc/globdoc2_0.asp"/>
			<scope>
				<mcc:MD_Scope>
					<mcc:level>
						<mcc:MD_ScopeCode codeListValue="dataset" codeList="http://standards.iso.org/iso/19115/resources/Codelist/cat/codeLists.xml#MD_ScopeCode"/>
					</mcc:level>
				</mcc:MD_Scope>
			</scope>
			<role>
				<GUF_TargetRoleCode codeListValue="primary" codeList="http://www.opengis.net/guf/1.0/resources/codeList.xml#GUF_TargetRoleCode"></GUF_TargetRoleCode>
			</role>
		</GUF_FeedbackTarget>
	</target>
</GUF_FeedbackItem>
