== Scope
[NOTE]
====
This OGC™ Standard defines an XML encoding for encoding user feedback about geospatial datasets or metadata records describing datasets. This standard reuses and extends the ISO 19115-1:2014 model and follows the ISO 19139 encoding rules. The XML encoding is based on the Geospatial User Feedback Conceptual Model Standard [OGC 15-097].

This OGC® Standard is applicable to metadata catalogue servers and clients that want to exchange geospatial user feedback information.

This OGC® Standard is defined to allow implementation of catalogue clients that are able to complement the discovery of geospatial datasets. Catalogue clients present query results, commonly based on summaries of detailed metadata records created and maintained by the producers. With this standard, the metadata responses can also provide user feedback summaries and detailed user feedback reports. Clients using this standard can provide a user interface to support provision of additional comments or inquiries about datasets or to complement the producer metadata by presenting additional user feedback information about the data.

Geospatial User Feedback as used in this standard encompasses: user comments, questions and answers, user reports of dataset problems and proposed solutions to those problems, ratings, usage reports, citations of related datasets or publications describing usage, quality reports, relevant additional provenance information, significant events related to the use or interpretation of a dataset.

This standard does not define any query language to request or send user feedback to/from metadata catalogues.


====
