.Preface

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

_Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation._


//[NOTE]
//====
//Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work.
//====

////
//*OGC Declaration*
////

// NOTE: Uncomment ISO section if necessary

//*ISO Declaration*

//ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

//International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

//The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

//Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.

[abstract]
== Abstract

TheOGC Geospatial User Feedback Standard version 2 - XML Encoding Extension is based on the OGC Geospatial User Feedback conceptual model [2]. Geospatial User Feedback (GUF) is metadata that is produced primarily by the consumers of geospatial data products based on their use and experience with those products. The GUF Standards complement the existing metadata conventions whereby documents recording dataset characteristics and production workflows are generated by the creator, publisher or curator of a data product. As a part of metadata, the GUF data model internally reuses some elements of ISO 19115-1 (the updated version of the OGC Abstract Specification topic 11  $$faltaLink) but not the general structure. This selective use of ISO metadata elements prioritizes future interoperability with developing ISO metadata models.

This Standard can be used in combination with [2]. In the future, other encodings may be considered, an alternative could use the JSON-LD encoding based on parts of schema.org.

The OGC Geospatial User Feedback Standard version 2 - XML Encoding Extension is based on work done in two European Union 7th Framework program projects called GeoViQua (FP7 FP7/2007-2013 under grant agreement n°265178) and CHARMe (FP7/2007-2013 under grant agreement n°312641). GeoViQua considers user feedback as part of the metadata that enables users to assess the quality and fitness-for-use of geospatial datasets. The GeoViQua participants developed its quality model based on ISO 19115-1:2014 and drafts of ISO19157:2013. The GeoViQua model is divided into the Producer Quality Model and the User Feedback Model. Both models are encoded in XML based on the ISO 19139 rules. The GeoViQua User Feedback Model footnote:[http://schemas.geoviqua.org] formed the initial basis of the XML Encoding Extension defined in this Standard. CHARMe also focused on developing means for users to annotate datasets. The approach used in that project was based on W3C annotations and developed annotation conventions in RDF. Parts of the CHARMe conceptual model are incorporated in the OGC GUF standards.

////
If security considerations have been made for this Standard, follow the examples found in IANA or IETF documents. Please see the following example.
“VRRP is designed for a range of internetworking environments that may employ different security policies. The protocol includes several authentication methods ranging from no authentication, simple clear text passwords, and strong authentication using IP Authentication with MD5 HMAC. The details on each approach including possible attacks and recommended environments follows.
Independent of any authentication type VRRP includes a mechanism (setting TTL=255, checking on receipt) that protects against VRRP packets being injected from another remote network. This limits most vulnerabilities to local attacks.
NOTE: The security measures discussed in the following sections only provide various kinds of authentication. No confidentiality is provided at all. This should be explicitly described as outside the scope....”
////

// Submitting organizations inserted here by Metanorma

//The following organizations submitted this Document to the Open Geospatial Consortium Inc.

:submitting-organizations: UAB-CREAF; Aston University
//; Fraunhofer Institute; 52 North

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
.Submitters
|===
|*Name* |*Affiliation*
// | Name	Company
|Joan Masó | UAB-CREAF
| Alaitz Zabala | UAB-CREAF
| Oscar González | UAB-CREAF
|Lucy Bastin | Aston University
// |Simon Thum	| Fraunhofer Institute
// |Daniel Nust | 52 North
|===

//== Contributors

//This clause is optional.

//Additional contributors to this Standard include the following:

//Individual name(s), Organization
