== *Annex A: Conformance Class Abstract Test Suite (Normative)*

A GUF XML implementation of this standard must satisfy the following system characteristics to be conformant with this specification.


=== *A.1	Conformance class: Quality Common*

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/geospatial-user-feedback-xml/1.0/conf/quality-common

Tests identifiers below are relative to http://www.opengis.net/spec/geospatial-user-feedback-xml/1.0

==== A.1.1	MIME type

[[ats_example1]]
[conformance_class_example1]
====
[%metadata]
Test id:: *conf/quality-common/mime-type*
Test Purpose:: include::../requirements/requirement001.adoc[]
Test method:: Validate the MIME type +
Test passes if the encoded instances have the associated MIME type application/xml.

====

==== A.1.2	File extension

//include::./ATS_test_example1.adoc[]

[[ats_example2]]
[conformance_class_example1]
====
[%metadata]
Test id:: */conf/quality-common/file-extension*
Test Purpose:: include::./requirement002.adoc[]
Test method:: Validate the file extension +
Test passes if a file system is used and the encoded instances are files with ‘.xml’ file extension

====

==== A.1.3	ISO XML rules

//include::./ATS_test_example2.adoc[]

[[ats_example3]]
[conformance_class_example1]
====
[%metadata]
//Test id:: */conf/quality-common/file-extension*
Test id:: */conf/quality-common/encoding-rules*
Test Purpose:: include::./requirement003.adoc[]
Test method:: Validate the encoding rules followed +
Test passes if the encoded instances follow ISO-19139 conformance classes.

====

==== A.1.4	ISO XML schema

[[ats_example4]]
[conformance_class_example1]
====
[%metadata]
Test id:: */conf/quality-common/iso-schema*
Test Purpose:: include::./requirement004.adoc[]

Test method:: Validate the XML against the right XML schema +
Test passes if encoded instances validates under the ISO XML schemas for ISO19115-1 and ISO19157-1 that are provided by ISO19115-3 and ISO19157-2 respectively.

====

==== A.1.5	Quality common XML schema

[[ats_example5]]
[conformance_class_example1]
====
[%metadata]
Test id:: */conf/ quality-common/qcm-schema*
Test Purpose:: include::./requirement005.adoc[]
Test method:: Validate the XML against the right XML schema +
Test passes if XML elements of the data type QCM_Publication and QCM_DiscoveredIssue conform to the http://www.opengis.net/spec/geospatial-user-feedback/1.0/conf/quality-common and validate against the quality common schema with the XML namespace http://www.opengis.net/guf/1.0/common and encoded in the qcm.xsd

====