[[Clause_Critical]]
== Description of critical changes

//=== <short name for the change>
//<details of the change>
The changes described below are critical as they involve changes in the XML encoding that will result in validation errors in documents based on version 1.0 of the GUF.

=== ED-03: "problemDateTime" Element Data Type Changes

In GUF version 1.0, Table 5 in section 6.3 describes the QCM_DiscoveredIssue Data Type which is used to report issues found while using a certain resource.

QCM_DiscoveredIssue contains an element named "problemDateTime" designed to define the date and time a problem is detected by a user of that resource.

In GUF v.1.0, "problemDateTime" was defined as a CI_Date element, requiring users to specify both a "date" and a "dateType." This could lead to inconsistencies with the "problemDateTime" element definition. As the "type of date" is included in the element name itself, no "dateType" is needed. Therefore, GUF v.2.0 updates the "problemDateTime" data type from "CI_Date" to "DateTime."

=== ED-04: "expectedFixDate" Element Data Type Changes

Similar to ED-03.

In GUF version 1.0, Table 5 in section 6.3 describes the QCM_DiscoveredIssue Data Type and is used to report issues found while using a certain resource.

QCM_DiscoveredIssue contains an element named "expectedFixDate" designed to define the date when a solution is expected to be released by the provider in the form of a "fixedResource" or directly as a fix in the original target resource.

In GUF v.1.0, "expectedFixDate" was defined as a CI_Date element, requiring users to specify both a "date" and a "dateType." This could lead to inconsistencies with the "expectedFixDate" element definition. As the "type of date" is included in the element name itself, no "dateType" is needed. Therefore, GUF v.2.0 updates the "expectedFixDate" data type from "CI_Date" to "Date."

=== ED-11: GUF_FeedbackItem Data Type Element Name Update

For clarity purposes, Table 7 in section 7.2 describing GUF_FeedbackItem data type, the GUF v.1.0 "additionalLineage" element name is updated to "additionalLineageSteps" in the version 2.0. This element is defined as "Additional lineage steps not included in the producer metadata," making the new element name more self-explanatory.

=== ED-12: "userDetails" Element Data Type Changes

GUF v.1.0 GUF_UserInformation Data Type included the element "userDetails" defined as a CI_Responsibility type element and also a "userRole" element defined as GUF_UserRoleCode.

As CI_Responsibility Data Type contains an element named "role," inconsistencies with the role described in the "userRole" element may appear.

To avoid this source of inconsistencies, GUF v.2.0 changes the "userDetails" element Data Type to CI_Party.

=== ED-14: "applicationDomain" Data Type Changes

In GUF version 1.0, the GUF_UserInformation class had two attributes: applicationDomain (a set of text strings that could contain multiple values, i.e., CharacterString [0..*]) and expertiseLevel (a single value of type GUF_RatingCode). This setup allowed multiple application domains to be associated with a user, but only one expertise level could be defined.

This design presented a significant issue: there was no way to specify which application domain the expertise level referred to. This was problematic because it is likely that a user may have different levels of expertise for different application domains, but the current configuration could not represent this distinction adequately.

To fix this issue, the original "expertiseLevel" attribute is deprecated, and the "applicationDomain" attribute type is now GUF_ApplicationDomain Data Type and has a [1..*] cardinality. This data type allows documenting several "domains" (Character String) and the "expertiseLevel" (GUF_RatingCode) corresponding to each of them.

Related to ED-15 substantive change.

=== ED-20: Updating Element Names in UFS_FeedbackSummary

In the GUF v.1.0 Standard, UFS_FeedbackSummary contained two elements named "minimumPossibleRating" and "maximumPossibleRating." The names of these elements suggest the minimum and maximum of the scale of rating used, but their description indicates that their content is the minimum and maximum rating received among all the feedback items for a particular resource.

To clarify the meaning of these elements, GUF v.2.0 overwrites "minimumPossibleRating" and "maximumPossibleRating" elements with "minimumRating" and "maximumRating" elements.

=== ED-21: UFS_FeedbackSummary New "numberOfReproducibleUsageReports" Element

As GUF v.2.0 adds the QCM_ReproducibleUsage class to the model (see ED-07 and ED-08) it is relevant to add a new element "numberOfReproducibleUsageReports" to UFS_FeedbackSummary Data Type. This element is mandatory, and is used to document the total number of populated reproducible usage reports for a particular resource.

//If no critical changes are present, use the phrase below.
//There are no critical changes in this release.
