.Preface

This document provides Release Notes for OGC Geospatial User Feedback (GUF) Standard. Conceptual Model. v.2.0 <<OGC23-017>> and does not modify that Standard.

This document provides the details of edits, deficiency corrections, and enhancements of the above-referenced standard. It also documents those items that have been deprecated. Finally, this document provides implementation details related to issues of backwards compatibility.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[abstract]
== Abstract

Geospatial User Feedback is metadata that is predominantly produced by the consumers of geospatial data products based on their use and experience with those products. The GUF Standard complements the existing metadata conventions whereby documents recording dataset characteristics and production workflows are generated by the creator, publisher or curator of a data product. As a part of metadata, the GUF data model internally reuses some elements of ISO 19115-1 (the updated version of the OGC Abstract Specification Topic 11 - Metadata) but not the general structure. This selective use of ISO metadata elements prioritizes future interoperability with developing ISO metadata models.

The first version of the GUF conceptual model was approved as an OGC Standard in 2016-05-25. GUF v.2.0 extends the original model by including the description of reproducible usage of a certain resource and corrects issues in several elements. This document describe 7 critical changes, 6 substantive changes and 9 administrative changes including Data Type changes, element name changes, new elements descriptions, cardinality changes and new classes and requirements among several minor text explanation corrections. This document details the changes between the two versions.

Even if most of the changes are additions or error fixes, any addition to an XML document results in validation error if an old application uses the previous version of the XML schemas. That is why we decided not to call the XML encoding part a v1.1 but a v2.0. The conceptual model could still be called v1.1 (because there is no significant change to the old version concepts) but this will create confusion with the decided version of the XML encoding. In the end it was decided to keep the version numbers synchronized to 2.0. 


== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

.Submitters
|===
|*Name* |*Affiliation*
| Joan Masó | UAB-CREAF
| Alaitz Zabala | UAB-CREAF
| Oscar González | UAB-CREAF
|===




