[abstract]
== Abstract

This standard defines a conceptual Geospatial User Feedback (GUF) data model. Geospatial User Feedback is metadata that is predominantly produced by the consumers of geospatial data products as they use and gain experience with those products. This standard complements existing metadata conventions whereby documents recording dataset characteristics and production workflows are generated by the creator, publisher or curator of a data product. As a part of metadata, the GUF data model reuses some elements of ISO 19115-1:2014 (the updated version of the OGC Abstract Specification topic 11) but not the general structure. This selective use of ISO metadata elements prioritizes future interoperability with developing ISO metadata models. This standard is designed to be used combination with an encoding standard. Initially an XML encoding following the ISO19139 encoding rules is specified in a separate OGC standard (OGC 15-098). In the future other encodings may be defined, including such as the use of JSON-LD, based on parts of schema.org.

== Keywords

//Keywords inserted here by Metanorma

The following are keywords to be used by search engines and document catalogues.

ogcdoc, ogc documents, user feedback, metadata, fitness-for-use, geospatial

== Preface

[NOTE]
====
This standard is based on work done in two European Union 7th Framework program projects called GeoViQua (FP7 FP7/2007-2013 under grant agreement n째265178) and CHARMe (FP7/2007-2013 under grant agreement n째312641). GeoViQua considers user feedback as part of the metadata that allows users to assess the quality and fitness-for-use of geospatial datasets. GeoViQua developed its quality model based on ISO 19115-1:2014 and drafts of ISO19157:2013. The GeoViQua model is divided into the Producer Quality Model and the User Feedback Model. Both models are encoded in XML based on the ISO 19139 rules. The GeoViQua User Feedback Model (footnote:[http://schemas.geoviqua.org]) formed the initial basis of the model defined in this standard. CHARMe also focused on developing means for users to annotate datasets. The approach used in that project was based on W3C annotations and developed annotation conventions in RDF. Parts of the CHARMe conceptual model have been incorporated in the OGC GUF standards.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====

== Security considerations

No security considerations have been made for this Standard.


== Submitting organizations

// Submitting organizations inserted here by Metanorma

The following organizations submitted this Document to the Open Geospatial Consortium Inc. 

UAB-CREAF +
Aston University +
Fraunhofer Institute +
52 North 


== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name* |*Affiliation*
| Joan Mas처 | UAB-CREAF
| Lucy Bastin | Aston University
| Simon Thum | Fraunhofer Institute
| Daniel N체st | 52 North
|===

//== Contributors

//This clause is optional.

//Additional contributors to this Standard include the following:

//Individual name(s), Organization
