== Conventions

=== Data dictionary tables

//This sections provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

//=== Identifiers
//The normative provisions in this standard are denoted by the URI

//`http://www.opengis.net/spec/{standard}/{m.n}`

//All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

The data dictionary for the GUF Conceptual Model is specified in a series of tables. The contents of the columns in these tables are described in <<tbl_contents>>.

[#tbl_contents,reftext='{table-caption} {counter:table-num}']
.Contents of data dictionary tables
[width = "100%",options="header"]
|===
|*Column title* | *Column contents* 
|Name 
(left column) |_"name"_ is the UML model attribute or association role name. +
The _name_ capitalization rules used are specified in Subclause 11.6.2 of OGC 06-121r9 [1]. Some _names_ in the tables may appear to contain spaces, but no _names_ contain spaces. + 
Examples: "target", "itemIdentifier"
|Definition 
(second column) | Specifies the definition of this element (omitting unnecessary words such as “a”, “the”, and “is”). If the element aims to contain the identifier of something, not a description or definition, the definition of this element should read something like “Identifier of ...”. +
Examples: "Link to the actual geospatial resource the publication is about.", "Identifier for the feedback item"
| Data type and value (third column) or Data type 
(if
 no second items are included in rows of table)
| Normally contains two items: +
The first item is often the data type used for this element, using data types appropriate in a UML model, in which this element is a named attribute of a UML class. Alternately, the first item can identify the data structure (or class) referenced by this association, and references a separate table used to specify the contents of that class (or data structure). +
The optional second item in the third column of each table should indicate the source of values for this element, the alternative values, or other value information, unless the values are quite clear from other listed information. +
Examples: "ISO 19115-1 CI_Citation data type (ISO 19115-1:2014 B.3.2.1)", "MD_Identifier (ISO 19115-1:2014 B.3.3.3)"
|Multiplicity and use (right or fourth column)
or Multiplicity (if are no second items are included in rows of table) 
|Normally contains two items: +
The first item specifies the multiplicity and optionality of this element in this data structure, either “One (mandatory)”, “One or more (mandatory)”, “Zero or one (optional)”, or “Zero or more (optional)”. +
The second item in the right column of each table specifies how any multiplicity other than “One (mandatory)” is used. If that element is optional, under what condition(s) shall that element be included or not included?  If that element can be repeated, for what is that parameter repeated? +
Example: "Zero or more (optional). If the target of the citation is specified by another part of the data model this parameter should not be used.", "One (mandatory)" 
|===

When the data type in the third column is an enumeration or a code list, and the list of possible values is too extensive, the values and their meanings are detailed in a separate table. This separate table is then referenced in the third column of the original table row.

The data type of many parameters, in the third table column, is specified as “Character String type, not empty”.

The content of these data dictionary tables are normative, including any table footnotes.

In the data dictionary tables three background colors are used:

* grey is used when the class is an extension on a previous one, so those are the inherited elements, defined in the original class (e.g. in CI_CItation which us extended by QCM_Publication)
* green is used to identify elements that have been added from the first version of the GUF conceptual model defined in OGC 15-097r1 [7].
* blue is used to identify elements that have changed from the first version of the GUF conceptual model defined in OGC 15-097r1 [7].

Thus, elements with no background color in the dictionary tables have not changed from the first version of the conceptual model or the change is only in the description (for clarity) but not in the element itself. The use of background colors in the dictionary tables is intended to allow a reader to better identify changes from the GUF conceptual model v.1.0.

=== UML Notations

Unified Modeling Language (UML) static structure diagrams appearing in this standard are used as described in Sub clause 5.2 of OGC Web Service Common OGC 06-121r9 [1]. Further, the following conventions hold:

*	UML elements in white color come from ISO 19115-1:2014 [5] or ISO 19157:2013 [3].
*   UML element names with prefix QCM (Quality Common Metadata) are those defined in the http://www.opengis.net/spec/geospatial-user-feedback/2.0/req/quality-common requirements class of this Standard.
*	UML element names with prefix GUF (Geospatial User Feedback) are those defined in the http://www.opengis.net/spec/geospatial-user-feedback/2.0/req/feedback-item requirements class of this Standard.
*	UML element names with prefix UFS (User Feedback Summary) are those defined in the http://www.opengis.net/spec/geospatial-user-feedback/2.0/req/feedback-summary requirements class of this Standard.
*	UML element names with prefix UFC (User Feedback Collection) are those defined in the http://www.opengis.net/spec/geospatial-user-feedback/2.0/req/feedback-collection requirements class of this Standard.

=== Core and Extension Breakdown

The OGC Geospatial User Feedback (GUF) Standard follows the modular specification design pattern as described in OGC 08-131r3 [6]. The contributors to the GUF Standard decided that the requirements would be split into a core (quality common and geospatial user feedback item) and extensions for summary statistics and geospatial user feedback collections. In addition, other standards in the GUF series will potentially provide specific encodings of the data model specified in this document. For example, the OGC Geospatial User Feedback Standard OGC 23-061 [8] XML Encoding Extension v 2.0 is initially provided for this v.2.0 of the conceptual model. A JSON encoding is expected in the near future.
