.Preface

[NOTE]
====
The first version of this conceptual model (OGC 15-097r1) was based on work done in two European Union 7th Framework program projects called GeoViQua (FP7/2007-2013 under grant agreement n°265178) and CHARMe (FP7/2007-2013 under grant agreement n°312641).

During the H2020 NextGEOSS project (grant agreement No 730329), an implementation for Geospatial User Feedback (GUF) v.1.0 was created. During this implementation several improvements on the conceptual model were identified, mainly to avoid possible inconsistencies when documenting feedback items of a certain resource. Moreover, an extension of the GUF conceptual model to store reproducible usage (as a way of capturing knowledge) was defined in H2020 NextGEOSS project and refined in the H2020 EIFFEL project (grant agreement No 101003518). The result of these efforts are the main elements included or modified in this version 2.0 of the GUF conceptual model, which is being developed also related to the H2020 ILIAD project (grant agreement No 101037643).

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

_Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation._
====

[abstract]
== Abstract
{set:bgcolor:#D5F5E3}
This standard defines the version 2.0 of the conceptual Geospatial User Feedback (GUF) data model (v.1.0 is included in OGC 15-097r1). Geospatial User Feedback is metadata that is predominantly produced by the consumers of geospatial data products as they use and gain experience with those products. GUF v.2.0 extends the original conceptual model mainly by including the description of reproducible usage of a certain resource.

This standard complements existing metadata conventions whereby documents recording dataset characteristics and production workflows are generated by the creator, publisher or curator of a data product. As a part of metadata, the GUF data model reuses some elements of ISO 19115-1:2014 (the updated version of the OGC Abstract Specification topic 11) but not the general structure. This selective use of ISO metadata elements prioritizes future interoperability with developing ISO metadata models. 

This standard is designed to be used combination with an encoding standard. An XML encoding for this version 2.0 of the conceptual model following the ISO19139 encoding rules is specified in a separate OGC standard (OGC 23-061). In the near future a JSON encoding will be also developed.

//== Keywords

//Keywords inserted here by Metanorma $$

//The following are keywords to be used by search engines and document catalogues.

:keywords: ogcdoc, ogc documents, user feedback, metadata, fitness-for-use, geospatial

//== Security considerations

//No security considerations have been made for this Standard.


//== Submitting organizations

// Submitting organizations inserted here by Metanorma

//The following organizations submitted this Document to the Open Geospatial Consortium Inc.

:submitting-organizations: UAB-CREAF; Aston University 
//; Fraunhofer Institute

[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
.Submitters
|===
|*Name* |*Affiliation*
| Joan Masó | UAB-CREAF
| Alaitz Zabala | UAB-CREAF
| Oscar González | UAB-CREAF
| Lucy Bastin | Aston University
// | Simon Thum | Fraunhofer Institute
|===

//== Contributors

//This clause is optional.

//Additional contributors to this Standard include the following:

//Individual name(s), Organization
