== Terms and Definitions

This document uses the terms defined in Sub-clause 5.3 of OGC 06-121r9 [1], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard. It also uses definitions from the first version of the conceptual model OGC 15-097r1:2016 [7].

For the purposes of this document, the following additional terms and definitions apply.

*4.1* +
*citation* +
information object containing information that directs a reader's or user's attention from one resource to another (ISO 24619:2011 [2], 3.1.16)

*4.2* +	
*item* +
anything that can be described and considered separately (ISO 19157:2013 [3], 4.18)

*4.3* +
*metadata* +
information about a resource (ISO 19115-1:2014 [4], 4.10)

*4.4* +
*quality* +
degree to which a set of inherent characteristics fulfils requirements (ISO 9000:2005 [5], 3.1.1)

*4.5* +
*rating* +
component of a user feedback item that subjectively classifies a resource in a short list of ordered categories (OGC 15-097r1:2016 [7], 4.5)
NOTE 1: The five star system is one of the most popular rating systems in the web. 5 stars means very good and 1 star means very bad.

*4.6* +
*user* +
consumer of a resource (OGC 15-097r1:2016 [7], 4.6)

*4.7* +
*user comment* +
component of a user feedback item providing textual information with no structure (OGC 15-098r1:2016 [7], 4.7)

*4.8* +
*user feedback* +
information about a resource directly provided by users (OGC 15-097r1:2016 [7], 4.8)

*4.9* +
*user feedback item* +
unit of information provided by a user about related resources as a result of its usage (OGC 15-097r1:2016 [7], 4.9)

*4.10* +
*user feedback collection* 
collection of feedback items that are grouped by criteria, or are the result of a query (OGC 15-097r1:2016 [7], 4.10)

*4.11* +
*user feedback summary* +
statistical summary of a feedback collection (OGC 15-097r1:2016 [7], 4.11)

