== Terms and Definitions

This document uses the terms defined in Sub-clause 5.3 of OGC 06-121r9 [1], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard. It also uses definitions from the first version of the conceptual model OGC 15-097r1:2016 [7].

For the purposes of this document, the following additional terms and definitions apply.


=== citation

information object containing information that directs a reader's or user's attention from one resource to another

[.source]
<<ISO24619:2011>>

=== item

anything that can be described and considered separately

[.source]
<<ISO19157:2013>>

=== metadata

information about a resource

[.source]
<<ISO19115-1:2014>>

=== quality

degree to which a set of inherent characteristics fulfils requirements

[.source]
<<ISO9000:2005>>

=== rating

component of a user feedback item that subjectively classifies a resource in a short list of ordered categories

NOTE 1: The five star system is one of the most popular rating systems in the web. 5 stars means very good and 1 star means very bad.

[.source]
<<OGC15-097r1>>

=== user

consumer of a resource

[.source]
<<OGC15-097r1>>

=== user comment

component of a user feedback item providing textual information with no structure

[.source]
<<OGC15-098r1>>

=== user feedback

information about a resource directly provided by users

[.source]
<<OGC15-097r1>>

=== user feedback item

unit of information provided by a user about related resources as a result of its usage

[.source]
<<OGC15-097r1>>

=== user feedback collection

collection of feedback items that are grouped by criteria, or are the result of a query

[.source]
<<OGC15-097r1>>

=== user feedback summary

statistical summary of a feedback collection

[.source]
<<OGC15-097r1>>