== Scope

This OGC™ Standard defines a data model for encoding user feedback about geospatial datasets or metadata records describing datasets. This version of the GUF Standard reuses and extends version 1.0 of the GUF conceptual model (OGC 15-097r1) as well as the ISO 19115-1:2024 data model. A set of information classes is defined.

This OGC® Standard is applicable to metadata catalogue servers and clients that want to exchange geospatial user feedback information.

This OGC® Standard is defined to support implementation of catalogue clients that are able to complement the discovery of geospatial datasets. Catalogue clients present query results, commonly based on summaries of detailed metadata records created and maintained by the producers. Implementation of this Standard enable clients to present user feedback summaries and detailed user feedback reports. Clients implementing this Standard can provide a user interface to capture use input and comments for datasets or to complement the producer metadata by presenting user feedback information about the data or its metadata.

Geospatial User Feedback as used in this Standard encompasses: User comments, questions and answers, user reports of dataset problems and proposed solutions to those problems, ratings, usage reports, reproducible usage reports, citations of related datasets or publications describing usage, quality reports, relevant additional provenance information, significant events related to the use or interpretation of a dataset.

This Standard neither defines an encoding nor a query language to request or send user feedback to catalogues. 

