== Terms and definitions

This document uses the terms defined in Sub-clause 5.3 of [OGC06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

*4.1* +
*citation* +
information object containing information that directs a reader's or user's attention from one resource to another [ISO 24619:2011, 3.1.16]

*4.2* +	
*item* +
anything that can be described and considered separately [ISO 19157:2003, 4.18]

*4.3* +
*metadata* +
information about a resource [ISO 19115-1:2014, 4.10]

*4.4* +
*quality* +
degree to which a set of inherent characteristics fulfils requirements [ISO 9000:2005, 3.1.1]

*4.5* +
*rating* +
component of a user feedback item that subjectively classifies a resource in a short list of ordered categories
NOTE 1: The five star system is one of the most popular rating systems in the web. 5 stars means very good and 1 star means very bad.

*4.6* +
*user* +
consumer of a resource

*4.7* +
*user comment* +
component of a user feedback item providing textual information with no structure

*4.8* +
*user feedback* +
information about a resource directly provided by users

*4.9* +
*user feedback item* +
unit of information provided by a user about related resources as a result of its usage

*4.10* +
*user feedback collection* 
collection of feedback items that are grouped by criteria, or are the result of a query

*4.11* +
*user feedback summary* +
statistical summary of a feedback collection

