== Introduction

=== Scope

//short scope of the standard and the general nature of changes

This OGC™ Standard defines a data model for encoding user feedback about geospatial datasets or metadata records describing datasets. It reuses and extends the ISO 19115-1:2024 data model. A set of information classes is defined.

This OGC® Standard is applicable to metadata catalogue servers and clients that want to exchange geospatial user feedback information.

This OGC® Standard is defined to allow implementation of catalogue clients that are able to complement the discovery of geospatial datasets. Catalogue clients present query results, commonly based on summaries of detailed metadata records created and maintained by the producers. Implementation of this standard allows clients to present user feedback summaries and detailed user feedback reports. Clients implementing this standard can provide a user interface to capture use input and comments for datasets or to complement the producer metadata by presenting user feedback information about the data or its metadata.

Geospatial User Feedback as used in this standard encompasses: user comments, questions and answers, user reports of dataset problems and proposed solutions to those problems, ratings, usage reports, citations of related datasets or publications describing usage, quality reports, relevant additional provenance information, significant events related to the use or interpretation of a dataset.

Version 2.0 contains no breaking changes to previous versions, but does contain additions, clarifications as well as some new elements. Changes are summarized in this document.


=== Document contributor contact points

All questions regarding this document should be directed to the contacts provided below or the referenced standard editor(s).

.Contacts
[width="80%",options="header"]
|====================
|Name |Organization
|Joan Masó | UAB-CREAF
|Alaitz Zabala| UAB-CREAF
|Oscar González| UAB-CREAF
|====================
