.Preface

This document provides the set of revision notes for OGC® Geospatial User Feedback Standard <<OGC15-098r1>> - XML encoding and does not modify that standard.

This document provides the details of edits, deficiency corrections, and enhancements of the above-referenced standard. It also documents those items that have been deprecated. Finally, this document provides implementations details related to issues of backwards compatibility.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[abstract]
== Abstract

Geospatial User Feedback is metadata that is predominantly produced by the consumers of geospatial data products based on their use and experience with those products. The standard complements the existing metadata conventions whereby documents recording dataset characteristics and production workflows are generated by the creator, publisher or curator of a data product. As a part of metadata, the GUF data model internally reuses some elements of ISO 19115-1 (the updated version of the OGC Abstract Specification topic 11) but not the general structure. This selective use of ISO metadata elements prioritizes future interoperability with developing ISO metadata models.

The first version of the GUF conceptual model was approved as an OGC standard in 2016-05-25. GUF v.2.0 extends the original one mainly by including the description of reproducible usage of a certain resource.

This document reviews the changes between the two versions in detail.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

.Submitters
|===
|*Name* |*Affiliation*
| Joan Masó | UAB-CREAF
| Alaitz Zabala | UAB-CREAF
| Oscar González | UAB-CREAF
|===



