[[ats_core_api-definition-op]]
[abstract_test]
====
[%metadata]
identifier:: /conf/quality-common/citation-of-publications
target:: /req/quality-common/citation-of-publications
// label:: /conf/quality-common/citation-of-publications
// subject:: /req/quality-common/citation-of-publications

test-purpose:: The implementations of quality common _shall_ follow the UML model as shown in Figure 1. This model extends ISO 19115-1:2014 CI_Citation with elements for publications and the specification of the purpose of a citation by adding the properties specified in Table 2, Table 3 and Table 4. +
Dependency: ISO19115-1:2014 and ISO19157:2013 data models


[.component,class=test method]
=====
[.component,class=step]
--
Validate the requirements of publication citations.
--

[.component,class=step]
--
Test passes if publication citations instances are conformant to ISO 19115-1:2014 CI_Citation and point to the QCM_Publication data type and follow the data model specified in Table 2, Table 3 and Table 4.
--

// [.component,class=step]
//--
//Validate the contents of the returned document using test <<ats_core_api-definition-success,/conf/core/api-definition-success>>.
//--
=====
====
